# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e56268972da57b624840cd50883c4ac0f0bdce78d394cd2be9589b87c494a1a8edb3c3dfd2abfd400560cbe8b0164cd613c5516d534c1befb35643ca0246fe3b

test:
  secret_key_base: a4b8145ed399e33f13ed83fc361c74b7e020a4a70930a150abb8dda389702f35d2a7b603230fc5f1366428aa0326f813b66ca4428c24bf148280b127489e4c93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
